# Generated by Django 4.1 on 2022-08-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(upload_to='post/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('liked_user', models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.persona')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
