# Generated by Django 4.1 on 2022-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_liked_users_remove_post_likes_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
