# Generated by Django 4.1 on 2022-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_images_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
