# Generated by Django 4.1 on 2022-08-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultprofileid', models.IntegerField()),
                ('resultuserid', models.IntegerField()),
                ('resultusername', models.CharField(max_length=100)),
                ('resultfullname', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='search/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
